parameters:

    document_storage:

        # File hashing strategy
        # sha1 / md5 - ~10%
        strategy_file_hash: "md5"

        # Where are the files to be stored? (Trailing slash)
        # Default to %root_dir%/../document_storage/
        path_base: ~

        # How to split files up into directories
        # null - single directory
        # date - date based
        # hash - number of characters of hash of file
        #
        # Using date or hash then uses depth to determine how files are to be split up
        #
        directory_strategy: ~

        # Options (based on above option)
        #   date
        #     date_partial_day    (20150202)
        #     date_partial_month  (201502)
        #     date_partial_year   (2015)
        #   hash
        #     numeric (number of characters from front of sha1 hash)
        #
        directory_depth: ~

        # File storage strategy
        # database / file
        strategy_file: "file"

        # Text storage strategy
        # database / file
        strategy_text: "file"